FROM nginx:1.31.1

# configuration
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD curl -f http://localhost/ping || exit 1

CMD ["nginx", "-g", "daemon off;"]

